# Generated by Django 5.1.4 on 2025-03-23 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('team', '0002_team_logo'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='ai_score',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='player',
            name='stat',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
