# Generated by Django 5.1.4 on 2025-04-30 04:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('team', '0003_player_ai_score_player_stat'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='league',
            field=models.CharField(choices=[('kbo', 'KBO'), ('mlb', 'MLB')], default='mlb', max_length=10),
        ),
    ]
