# Generated by Django 5.1.4 on 2025-04-30 12:06

import team.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('team', '0004_team_league'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to=team.models.team_logo_path),
        ),
    ]
