# Generated by Django 5.1.4 on 2025-09-13 01:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("team", "0005_alter_team_logo"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="player",
            name="ai_score",
        ),
        migrations.RemoveField(
            model_name="player",
            name="school",
        ),
        migrations.RemoveField(
            model_name="player",
            name="stat",
        ),
    ]
