# Generated by Django 5.1.4 on 2025-03-24 05:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('match', '0002_schedule_scenario_team1_schedule_scenario_team2_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='schedule',
            name='score_team1',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='schedule',
            name='score_team2',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
