# Generated by Django 5.1.4 on 2025-03-25 06:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('match', '0003_schedule_score_team1_schedule_score_team2'),
    ]

    operations = [
        migrations.AddField(
            model_name='schedule',
            name='is_main_event',
            field=models.BooleanField(default=False),
        ),
    ]
