# Generated by Django 5.1.4 on 2025-05-05 07:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("match", "0005_schedule_league"),
    ]

    operations = [
        migrations.AddField(
            model_name="schedule",
            name="year",
            field=models.IntegerField(default=2025),
        ),
    ]
