# Generated by Django 5.1.4 on 2025-06-24 05:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("match", "0006_schedule_year"),
    ]

    operations = [
        migrations.AlterField(
            model_name="schedule",
            name="win_prob_team1",
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name="schedule",
            name="win_prob_team2",
            field=models.FloatField(default=0.0),
        ),
    ]
