# Generated by Django 5.1.4 on 2025-09-12 20:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("match", "0007_alter_schedule_win_prob_team1_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="schedule",
            name="scenario_team1",
        ),
        migrations.RemoveField(
            model_name="schedule",
            name="scenario_team2",
        ),
        migrations.RemoveField(
            model_name="schedule",
            name="win_prob_team1",
        ),
        migrations.RemoveField(
            model_name="schedule",
            name="win_prob_team2",
        ),
    ]
