# Generated by Django 5.1.4 on 2025-09-14 03:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="PlayerStatMLB",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("season", models.IntegerField(db_index=True, default=2025)),
                (
                    "league",
                    models.CharField(db_index=True, default="mlb", max_length=8),
                ),
                ("rank", models.IntegerField(db_index=True)),
                ("player", models.CharField(max_length=100)),
                ("age", models.IntegerField(blank=True, null=True)),
                ("team", models.CharField(db_index=True, max_length=8)),
                ("team_norm", models.CharField(db_index=True, max_length=8)),
                ("lg", models.CharField(db_index=True, max_length=8)),
                ("WAR", models.FloatField(blank=True, null=True)),
                ("G", models.IntegerField(blank=True, null=True)),
                ("PA", models.IntegerField(blank=True, null=True)),
                ("AB", models.IntegerField(blank=True, null=True)),
                ("R", models.IntegerField(blank=True, null=True)),
                ("H", models.IntegerField(blank=True, null=True)),
                ("_2B", models.IntegerField(blank=True, null=True)),
                ("_3B", models.IntegerField(blank=True, null=True)),
                ("HR", models.IntegerField(blank=True, null=True)),
                ("RBI", models.IntegerField(blank=True, null=True)),
                ("SB", models.IntegerField(blank=True, null=True)),
                ("CS", models.IntegerField(blank=True, null=True)),
                ("BB", models.IntegerField(blank=True, null=True)),
                ("SO", models.IntegerField(blank=True, null=True)),
                ("BA", models.FloatField(blank=True, null=True)),
                ("OBP", models.FloatField(blank=True, null=True)),
                ("SLG", models.FloatField(blank=True, null=True)),
                ("OPS", models.FloatField(blank=True, null=True)),
                ("OPS_plus", models.IntegerField(blank=True, null=True)),
                ("rOBA", models.FloatField(blank=True, null=True)),
                ("Rbat_plus", models.IntegerField(blank=True, null=True)),
                ("TB", models.IntegerField(blank=True, null=True)),
                ("GIDP", models.IntegerField(blank=True, null=True)),
                ("HBP", models.IntegerField(blank=True, null=True)),
                ("SH", models.IntegerField(blank=True, null=True)),
                ("SF", models.IntegerField(blank=True, null=True)),
                ("IBB", models.IntegerField(blank=True, null=True)),
                ("Pos", models.CharField(blank=True, max_length=50, null=True)),
                ("Awards", models.CharField(blank=True, max_length=100, null=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["-WAR", "rank"],
                "unique_together": {("season", "league", "player", "team_norm")},
            },
        ),
    ]
